/*
 * Stub for class com.esoxjem.movieguide.favorites.DoPrint
 * Generated by Sapphire Compiler (sc).
 */
package com.esoxjem.movieguide.favorites.stubs;


public final class DoPrint_Stub extends com.esoxjem.movieguide.favorites.DoPrint implements sapphire.common.AppObjectStub {

    sapphire.policy.SapphirePolicy.SapphireClientPolicy $__client = null;
    boolean $__directInvocation = false;

    public DoPrint_Stub () {
        super();
    }

    public DoPrint_Stub (int $param_int_1) {
        super($param_int_1);
    }


    public void $__initialize(sapphire.policy.SapphirePolicy.SapphireClientPolicy client) {
        $__client = client;
    }

    public void $__initialize(boolean directInvocation) {
        $__directInvocation = directInvocation;
    }

    public Object $__clone() throws CloneNotSupportedException {
        return super.clone();
    }



    // Implementation of printCount()
    public void printCount() {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                super.printCount();
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public void com.esoxjem.movieguide.favorites.DoPrint.printCount()";
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
