/*
 * Stub for class com.esoxjem.movieguide.favorites.FavoritesStoreManager
 * Generated by Sapphire Compiler (sc).
 */
package com.esoxjem.movieguide.favorites.stubs;


public final class FavoritesStoreManager_Stub extends com.esoxjem.movieguide.favorites.FavoritesStoreManager implements sapphire.common.AppObjectStub {

    sapphire.policy.SapphirePolicy.SapphireClientPolicy $__client = null;
    boolean $__directInvocation = false;

    public FavoritesStoreManager_Stub () {
        super();
    }


    public void $__initialize(sapphire.policy.SapphirePolicy.SapphireClientPolicy client) {
        $__client = client;
    }

    public void $__initialize(boolean directInvocation) {
        $__directInvocation = directInvocation;
    }

    public Object $__clone() throws CloneNotSupportedException {
        return super.clone();
    }



    // Implementation of getDoPrint()
    public com.esoxjem.movieguide.favorites.DoPrint getDoPrint() {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.getDoPrint();
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public com.esoxjem.movieguide.favorites.DoPrint com.esoxjem.movieguide.favorites.FavoritesStoreManager.getDoPrint()";
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((com.esoxjem.movieguide.favorites.DoPrint) $__result);
    }
}
