/*
 * Stub for class com.esoxjem.movieguide.details.ShowReviews
 * Generated by Sapphire Compiler (sc).
 */
package com.esoxjem.movieguide.details.stubs;


public final class ShowReviews_Stub extends com.esoxjem.movieguide.details.ShowReviews implements sapphire.common.AppObjectStub {

    sapphire.policy.SapphirePolicy.SapphireClientPolicy $__client = null;
    boolean $__directInvocation = false;

    public ShowReviews_Stub () {
        super();
    }

    public ShowReviews_Stub (com.esoxjem.movieguide.network.TmdbWebService $param_TmdbWebService_1) {
        super($param_TmdbWebService_1);
    }


    public void $__initialize(sapphire.policy.SapphirePolicy.SapphireClientPolicy client) {
        $__client = client;
    }

    public void $__initialize(boolean directInvocation) {
        $__directInvocation = directInvocation;
    }

    public Object $__clone() throws CloneNotSupportedException {
        return super.clone();
    }



    // Implementation of setTmdbWebService(TmdbWebService)
    public void setTmdbWebService(com.esoxjem.movieguide.network.TmdbWebService $param_TmdbWebService_1) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                super.setTmdbWebService( $param_TmdbWebService_1);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public void com.esoxjem.movieguide.details.ShowReviews.setTmdbWebService(com.esoxjem.movieguide.network.TmdbWebService)";
                $__params.add($param_TmdbWebService_1);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Implementation of getTmdbWebService()
    public com.esoxjem.movieguide.network.TmdbWebService getTmdbWebService() {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.getTmdbWebService();
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public com.esoxjem.movieguide.network.TmdbWebService com.esoxjem.movieguide.details.ShowReviews.getTmdbWebService()";
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((com.esoxjem.movieguide.network.TmdbWebService) $__result);
    }

    // Implementation of getReviews(String, TmdbWebService)
    public java.util.List getReviews(java.lang.String $param_String_1, com.esoxjem.movieguide.network.TmdbWebService $param_TmdbWebService_2) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.getReviews( $param_String_1,  $param_TmdbWebService_2);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public java.util.List<com.esoxjem.movieguide.Review> com.esoxjem.movieguide.details.ShowReviews.getReviews(java.lang.String,com.esoxjem.movieguide.network.TmdbWebService)";
                $__params.add($param_String_1);
                $__params.add($param_TmdbWebService_2);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((java.util.List) $__result);
    }

    // Implementation of getReviews(String)
    public java.util.List getReviews(java.lang.String $param_String_1) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.getReviews( $param_String_1);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public java.util.List<com.esoxjem.movieguide.Review> com.esoxjem.movieguide.details.ShowReviews.getReviews(java.lang.String)";
                $__params.add($param_String_1);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((java.util.List) $__result);
    }
}
